Home page
dimamaksymiuk01/Pets pull request #7
Opened 2024-04-29 09:42 UTC by dimamaksymiuk01

2024-04-29 18:19 UTC, Hahlina requested changes

2024-04-29 18:19 UTC, Hahlina commented on src/modules/Wrapper/Wrapper.tsx
> +import { WrapperStyled } from '@/modules/Wrapper/Wrapper.styled';
import { WrapperStyled } from './Wrapper.styled';

2024-04-29 18:19 UTC, Hahlina commented on src/modules/Wrapper/Wrapper.tsx
> +import { Poster } from '@/common/components/Poster/Poster';
import { Poster } from '@/common/components'

2024-04-29 18:19 UTC, Hahlina commented on src/store/themeSlice.ts
> +    getTheme: (state) => state,
getTheme: (state) => state - це зайве

2024-04-29 18:19 UTC, Hahlina commented on src/store/themeSlice.ts
> +    setTheme: (state, action: PayloadAction<THEME.LIGHT | THEME.DARK>) => {
PayloadAction<THEME.LIGHT | THEME.DARK>
type of
type of key of THEME_ENUM

2024-04-29 18:19 UTC, Hahlina commented on svgr.d.ts
> +declare module '*.svg' {
remove

2024-04-29 18:19 UTC, Hahlina commented on src/modules/HomeContent/components/LinksGroup/LinksCard/LinksCard.tsx
> +import Gallery from '@/public//pictures/gallery.png';
// - ?

2024-04-29 18:19 UTC, Hahlina commented on src/modules/HomeContent/components/LinksGroup/LinksCard/LinksCard.styled.tsx
> +  & > div:nth-child(1) {
& > div:nth-child - випилити

2024-04-30 12:00 UTC, dimamaksymiuk01 commented on src/common/hooks/useMount.tsx
> +  const [isMount, setIsMount] = useState(false);
не поняв))

2024-05-01 16:08 UTC, Hahlina approved these changes

2024-05-01 16:08 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/LinksGroup.tsx
> +    button: StyledButton,
button: StyledButton - прибери

2024-05-01 16:08 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/LinksGroup.tsx
> +    href: '/voting',
href: '/voting',   href: '/breeds',  href: '/gallery', - винеси в ROUTES

2024-05-01 16:08 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/LinksGroup.tsx
> +        <CardWithButtonContainer key={index}>
ми не використовуємо index, добав до масиву - id

2024-05-01 16:08 UTC, Hahlina commented on src/modules/Wrapper/Wrapper.styled.tsx
> +  gap: clamp(0.625rem, -8.446rem + 18.9vw, 8.563rem);
clamp потібно виносити кудись окремо і писати над ним комент, що він робить

2024-05-01 16:08 UTC, Hahlina commented on src/store/themeSlice.ts
> +    setTheme: (state, action: PayloadAction<THEME_ENUM.LIGHT | THEME_ENUM.DARK>) => {
спробуй просто THEME_ENUM

2024-05-04 14:41 UTC, Hahlina requested changes

2024-05-04 14:41 UTC, Hahlina commented on src/app/layout.tsx
> +/* components */
* components */ - після core, /* instruments */ - на низ
*

2024-05-04 14:41 UTC, Hahlina commented on src/common/hooks/useTheme.tsx
> +  const { currentTheme } = useAppSelector((state: RootState) => state.theme);
!

2024-05-04 14:41 UTC, Hahlina commented on src/common/hooks/useTheme.tsx
> +import { useAppDispatch, useAppSelector } from '@/common/hooks/stor';
import { useAppDispatch, useAppSelector } from '@/common/hooks'

2024-05-04 14:41 UTC, Hahlina commented on src/common/hooks/useTheme.tsx
> +      setTheme(currentTheme === THEME_ENUM.LIGHT ? THEME_ENUM.DARK : THEME_ENUM.LIGHT),
currentTheme === THEME_ENUM.LIGHT ? THEME_ENUM.DARK : THEME_ENUM.LIGHT) - в зміну винеси

2024-05-04 14:41 UTC, Hahlina commented on src/modules/Header/Header.tsx
> +/* instruments */
на низ

2024-05-04 14:41 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/LinksGroup.tsx
> +import { linksData } from './linksData';
import { linksData } from './linksData'; - components?

2024-05-04 14:41 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/linksData.ts
> +/* instruments */
на низ

2024-05-04 14:41 UTC, Hahlina commented on src/modules/NavMenu/components/LinksGroup/linksData.ts
> +    id: 0,
id: 0, - розпочни краще з 1

2024-05-04 14:41 UTC, Hahlina commented on src/store/themeSlice.ts
> +import { createSlice, PayloadAction } from '@reduxjs/toolkit';
пуста лінія

2024-05-04 14:41 UTC, Hahlina commented on src/store/themeSlice.ts
> +  currentTheme: THEME_ENUM.LIGHT | THEME_ENUM.DARK;
currentTheme: THEME_ENUM

2024-05-04 15:34 UTC, Hahlina approved these changes

2024-05-04 15:35 UTC, merged